# Site settings
title: PFunk
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: PFunk
user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: DJ/Producer
email: pfvnk.proton.me
# twitter_username: 
instagram_username: 
facebook_username: 
linkedin_username: 
github_username:
# medium_username:
# medium_url:
# gplus_username

exclude: ['package.json', 'src', 'node_modules', 'vendor']

